### ISSUE TITLE
Is it Possible to Extract Human Skeleton From Asus Xtion Camera Embedded on Pepper robot

### ISSUE THREAD

**Issue by TuyenNguyenTanViet** [AravinthPanch/gesture-recognition-for-human-robot-interaction#1]
Dear @AravinthPanch 
Do you think is it possible to extract human skeleton from Pepper 3D Camera as well as what you did in Nao robot + Asus Xtion?

**Comment by AravinthPanch** [comment]
Helllo @TuyenNguyenTanViet,
Unfortunately i haven't worked on Pepper, therefore i don't know about its camera. If the camera is OpenNI 2.0 compatible, then it should be possible to do that. Please check it out.
